apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fb-pvc3
  namespace: testfb-cs1
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
