apiVersion: v1
kind: Pod
metadata:
  name: file-browser-pod
  namespace: testfb-cs1
  labels:
    app: file-browser
spec:
  imagePullSecrets:
   - name: regcred
  containers:
   - name: file-browser-container
     image: quay.io/smitaraut/filebrowser:latest
     volumeMounts:
       - name: mypvc1
         mountPath: /srv
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc1
     persistentVolumeClaim:
       claimName: fb-pvc3
       readOnly: false
   - name: mypvc2
     persistentVolumeClaim:
       claimName: fb-pvc1
       readOnly: false
